- name: Install cron
  pacman:
    name:
      - cron
- name: Install cron job for ansible-pull
  cron:
    user: krzysztof
    name: ansible provision
    minute: */30
    job: "/usr/bin/ansible-pull -o -U https://github.com/<github_user>/ansible.git > /dev/null"
