- name: Install core packages
  pacman:
    name:
      - base-devel
      - git
  become: true
- name: Create symlink for git config
  file:
    src: "{{DOTFILES_DIR}}/git.conf"
    dest: ~/.gitconfig
    state: link
