- name: Install debugging tools for native programs
  pacman:
    name:
      - gdb
      - lldb
      - valgrind
      - strace
      - ltrace
      - linux-tools
  become: true
- name: Install debugging tools from AUR
  aur: name={{item}}
  with_items:
    - uftrace
  become: true
  become_user: aur
