- name: Install desktop environment packages
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xclip
      - xbindkeys
      - i3-wm
      - i3blocks
      - xss-lock
      - redshift
      - kitty
      - alacritty
      - ranger
      - dunst
      - rofi
      - rofi-calc
      - rofimoji
      - picom
      - feh
      - zathura
      - zathura-pdf-mupdf
      - zenity
      - ttf-dejavu
      - noto-fonts-emoji
      - arc-gtk-theme
      - arc-icon-theme
      - flameshot
      - xorg-xrandr
      - xdotool
  become: true
- name: Install desktop utils from pip
  pip:
    name:
      - keepmenu
    extra_args: --user
- name: Install desktop environment packages from AUR
  aur: name={{item}}
  with_items:
  - i3lock-color
  - ttf-iosevka
  - otf-jost

- name: Ensure .local/share/fonts dir exists
  file: path=~/.local/share/fonts state=directory
- name: Download nerd-font version of Iosevka
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Iosevka/Regular/complete/Iosevka%20Nerd%20Font%20Complete.ttf?raw=true
    dest: ~/.local/share/fonts/iosevka-nerd.ttf

- name: Create symlink for xinit run commands
  file:
    src: "{{DOTFILES_DIR}}/xinitrc"
    dest: ~/.xinitrc
    state: link

- name: Ensure .config dir exists
  file: path=~/.config/ state=directory

- name: Ensure i3 config dir exists
  file: path=~/.config/i3/ state=directory
- name: Create symlink for i3 config
  file:
    src: "{{DOTFILES_DIR}}/i3.conf"
    dest: ~/.config/i3/config
    state: link
- name: Clone i3blocks scripts
  git:
    repo: https://github.com/vivien/i3blocks-contrib
    dest: ~/.config/i3blocks
- name: Create symlink for i3blocks config
  file:
    src: "{{DOTFILES_DIR}}/i3blocks.conf"
    dest: ~/.config/i3blocks/config
    state: link

- name: Ensure rofi config dir exists
  file: path=~/.config/rofi/ state=directory
- name: Create symlink for rofi config
  file:
    src: "{{DOTFILES_DIR}}/rofi-config.rasi"
    dest: ~/.config/rofi/config.rasi
    state: link
- name: Create symlink for rofi theme
  file:
    src: "{{DOTFILES_DIR}}/rofi-theme.rasi"
    dest: ~/.config/rofi/theme.rasi
    state: link

- name: Ensure dunst config dir exists
  file: path=~/.config/dunst/ state=directory
- name: Create symlink for dunst config
  file:
    src: "{{DOTFILES_DIR}}/dunst.conf"
    dest: ~/.config/dunst/dunstrc
    state: link

- name: Ensure kitty config dir exists
  file: path=~/.config/kitty/ state=directory
- name: Create symlink for kitty config
  file:
    src: "{{DOTFILES_DIR}}/kitty.conf"
    dest: ~/.config/kitty/kitty.conf
    state: link

- name: Ensure alacritty config dir exists
  file: path=~/.config/alacritty/ state=directory
- name: Create symlink for alacritty config
  file:
    src: "{{DOTFILES_DIR}}/alacritty.yml"
    dest: ~/.config/alacritty/alacritty.yml
    state: link

- name: Create symlink for picom config
  file:
    src: "{{DOTFILES_DIR}}/picom.conf"
    dest: ~/.config/picom.conf
    state: link

- name: Ensure keepmenu config dir exists
  file: path=~/.config/keepmenu/ state=directory
- name: Create symlink for keepmenu config
  file:
    src: "{{DOTFILES_DIR}}/keepmenu.ini"
    dest: ~/.config/keepmenu/config.ini
    state: link

- name: Create symlink for passhole config
  file:
    src: "{{DOTFILES_DIR}}/passhole.ini"
    dest: ~/.config/passhole.ini
    state: link

- name: Ensure flameshot config dir exists
  file: path=~/.config/flameshot/ state=directory
- name: Create symlink for flameshot config
  file:
    src: "{{DOTFILES_DIR}}/flameshot.ini"
    dest: ~/.config/flameshot/config.ini
    state: link

- name: Create symlink for Xresources
  file:
    src: "{{DOTFILES_DIR}}/Xresources"
    dest: ~/.Xresources
    state: link
