- name: Install Emacs
  pacman: name=emacs
  become: true
- name: Clone doom-emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest:  ~/.emacs.d
- name: Create symlink for Emacs config
  file:
    src: "{{DOTFILES_DIR}}/doom"
    dest: ~/.doom.d
    state: link
