- name: Install Steam
  pacman:
    name:
      - steam
  become: true
- name: Install Minecraft launcher from AUR
  aur: name={{item}}
  with_items:
  - minecraft-launcher
  become: true
  become_user: aur
