- name: Install packages
  pacman: name={{item}}
  with_items:
  - xorg-server
  - xorg-xinit
  - xclip
  - xbindkeys
  - i3-wm
  - i3blocks
  - i3lock-color
  - redshift
  - termite
  - ranger
  - dunst
  - rofi
  - compton
  - feh
  - zenity
  - ttf-dejavu
- name: Install AUR packages
  aur: name={{item}}
  with_items:
  - sxlock-git
  - ttf-iosevka
  - otf-jost
