- name: Install hardware design packages
  pacman:
    name:
      - abc
      - iverilog
      - verilator
      - yosys
      - ghdl-llvm
      - freehdl
      - vtr
      - gtkwave
      - systemc
  become: true
- name: Install hardware design packages from AUR
  aur: name={{item}}
  with_items:
  - slang-verilog
  #- verible
  #- sv2v
  - svls
  - chisel
  become: true
  become_user: aur
- name: Install desktop utils from pip
  pip:
    name:
      - conda
      - edalize
      - fusesoc
      - cocotb
      - myhdl
    extra_args: --user
