- name: Install debugging tools for native programs
  pacman:
    name:
      - gdb
      - lldb
      - valgrind
      - strace
      - ltrace
  become: true
- name: Download gdb-dashboard
  get_url:
    url: https://git.io/.gdbinit
    dest: /home/krzysztof/dotfiles/gdb-dashboard
    mode: '0440'
