- name: Install packages
  pacman: name={{item}}
  with_items:
  - git
  - openssh
  - aspell
  - lsof
  - expect
  - inotify-tools
  - psmisc
  - sysstat
  - procps-ng
  - alsa-utils
  - playerctl
  - udisks2
  - zip
  - unzip
  - rclone
  - firefox
  - w3m
  - zathura
  - zathura-pdf-mupdf
  - steam
- name: Install AUR packages
  aur: name={{item}}
  with_items:
  - sxlock-git
  - spotify
