- name: Clone rEFInd theme
  git:
    repo: https://github.com/EvanPurkhiser/rEFInd-minimal
    dest: /boot/EFI/refind/themes/rEFInd-minimal
  become: true
- name: Test for rEFInd theme line in config
  lineinfile:
    state: absent
    path: /boot/EFI/refind/refind.conf
    line: "include themes/rEFInd-minimal/theme.conf"
  check_mode: true
  changed_when: false
  register: refind_theme_in_config
- name: Add rEFInd theme line to config
  lineinfile:
    state: present
    path: /boot/EFI/refind/refind.conf
    line: "include themes/rEFInd-minimal/theme.conf"
  when: refind_theme_in_config.found == 0
  become: true
