- name: Install Rust packages
  pacman:
    name:
      - rust-docs
      - rustup
      - rust-racer
      - rust-analyzer
      - cbindgen
  become: true
- name: Set default Rust toolchain
  command: rustup default stable
