- name: Ensures sudoers.d dir exists
  file: path=/etc/sudoers.d/ state=directory
- name: Copy sudoers
  copy: src=files/sudoers dest=/etc/sudoers.d/wheel owner=root group=root mode=0440
- name: Create group
  group: name=krzysztof gid=1000
- name: Create user
  user: name=krzysztof uid=1000 groups="krzysztof,wheel"
