- name: Install utility packages
  pacman:
    name:
      - man
      - man-pages
      - tealdeer
      - tmux
      - zellij
      - lsof
      - expect
      - inotify-tools
      - psmisc
      - procs
      - sysstat
      - procps-ng
      - htop
      - python-gobject # needed for udiskie
      - udisks2
      - zip
      - unzip
      - gzip
      - bzip2
      - p7zip
      - cloc
      - git-delta
      - wget
      - bat
      - fd
      - ripgrep
      - choose
      - hck
      - zellij
      - sd
      - sad
      - tree
      - mcfly
      - dust
      - duf
      - exa
      - zoxide
      - broot
      - github-cli
      - xplr
      - dog
      - bottom
      - below
      - entr
      - tokei
      - pv
      - up
      - xh
      - xsv
      - jq
      - jc
      - jo
      - gron
      - yq
      - plocate
      - moreutils
      - hexyl
      - mtr
      - bandwhich
  become: true
- name: Install utils from cargo
  pip:
    name:
      - erdtree
      - rm-improved
      - flcones
      - rnr
      - stringsext
- name: Install utils from pip
  pip:
    name:
      - ranger-fm
      - udiskie
      - passhole
      - grip
    extra_args: --user
- name: Create symlink for phmenu
  file:
    src: "{{DOTFILES_DIR}}/bin/phmenu"
    dest: ~/bin/phmenu
    state: link

- name: Ensure bat config dir exists
  file: path=~/.config/bat/ state=directory
- name: Create symlink for bat config
  file:
    src: "{{DOTFILES_DIR}}/batconfig"
    dest: ~/.config/bat/config
    state: link
