- name: Install utility packages
  pacman:
    name:
      - aspell
      - lsof
      - expect
      - inotify-tools
      - psmisc
      - sysstat
      - procps-ng
      - alsa-utils
      - playerctl
      - udisks2
      - zip
      - unzip
  become: true
- name: Install utils from pip
  pip: extra_args="--user --no-use-pep517"
    name:
      - pygments
      - ranger
      - udiskie
