- name: Install utility packages
  pacman:
    name:
      - aspell
      - lsof
      - expect
      - inotify-tools
      - psmisc
      - sysstat
      - procps-ng
      - alsa-utils
      - playerctl
      - python-gobject # needed for udiskie
      - udisks2
      - zip
      - unzip
  become: true
- name: Install utils from pip
  pip:
    name:
      - pygments
      - ranger
      - udiskie
    extra_args: "--user"
