- name: Install Neovim utils
  pacman:
    name:
      - fd
      - ripgrep
      - zk
  become: true
- name: Install Neovim
  pacman: name=neovim
  become: true

- name: Create symlink for Neovim config
  file:
    src: "{{DOTFILES_DIR}}/nvim"
    dest: ~/.config/nvim
    state: link

- name: Install Neovim plugins
  command: nvim '+PlugInstall | qa'
- name: Update Neovim plugins
  command: nvim '+PlugClean! | qa'
- name: Update Neovim plugins
  command: nvim '+PlugUpdate | qa'
