format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$memory_usage\
$gcloud\
$openstack\
$azure\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red)'

[directory]
truncation_symbol = '…/'
truncate_to_repo = false
