format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$character"""

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red)'

[directory]
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
style = "bold"

[git_commit]
style = "bold"

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"

[hostname]
style = "blue dimmed"

[localip]
style = "blue dimmed"

[username]
style_user = "bold blue"
