[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lucid-gen"
version = "0.1.0"
authors = [{ name="Krzysztof Biegański", email="krzysztof@biegan.ski" }]
license = { file = "Apache-2.0" }
description = "Lucid theme generator"
readme = "README.md"
dependencies = ["Jinja2 >= 3.1.3"]
requires-python = ">=3.10"

[project.scripts]
lucid-gen = "lucid_gen:main"

[tool.setuptools]
packages = ["lucid_gen"]

[tool.setuptools.package-data]
lucid_gen = ["*.jinja"]
